DevopsArtFactory/goployer

.github/CODEOWNERS

add_code_owner

---

README.md
configs/hello.yaml
pkg/aws/cloudwatch.go
pkg/aws/ec2.go
pkg/aws/elbv2.go
pkg/aws/ssm.go
pkg/builder/builder.go
pkg/deployer/bluegreen.go
pkg/deployer/deploy_manager.go
pkg/deployer/deployer.go
pkg/runner/rurnner.go
pkg/tool/slack.go

```
- Support minxedInstancePoilcy in autoscaling group.
- Support lifecycle callbacks to run commands before terminating instances.
- Add --slack-off cli argument to manually turn off slack notification.
- Add --log-level cli argument to set log level.
```

add mixed instances policy and few more configurations

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md 

add pr template

---

docs/config.toml
package-lock.json

fix base url

---

docs/config.toml

fix domain

---

.github/CODEOWNERS

add asbubam to OWNER

---

.gitignore
Makefile
deploy/Dockerfile
deploy/cross/Dockerfile

add release Makefile

---

Makefile
deploy/Dockerfile
docs/content/en/docs/Install/_index.md
hack/release.sh

installation with release version

---

pkg/runner/rurnner.go
pkg/tool/common.go

- Release code Added
- Use original account role for collector

install with release & use original account for collector

---

Makefile

Add formating before building application for pretty code.

add format command before building application

---

hack/schemas/main.go
pkg/builder/builder.go
pkg/builder/config.go
pkg/builder/metric_config.go

formatting

---

.circleci/config.yaml

setup circle ci

---

pkg/collector/collector.go
pkg/deployer/bluegreen.go
pkg/deployer/deployer.go

fix bug and add few more debug  messages

add few debug message and fix bug

---

.travis.yml
Makefile
codecov.yml
pkg/builder/builder.go
pkg/builder/builder_test.go
pkg/collector/collector.go
pkg/deployer/bluegreen.go

[force-merge]setup test

---

docs/content/en/_index.html
docs/content/ko/_index.html

Fix frontend bug and remove top message which is duplicated.

fix website front page

---

docs/content/en/_index.html
docs/content/en/docs/Install/_index.md
docs/content/ko/_index.html
docs/content/ko/docs/Install/_index.md

add brew with tap and modify command

modify brew command

---

pkg/aws/cloudwatch.go

fix cloudwatch getMetricData bug.
I did not reset date after searching one target group.. Fixed it and add log for better logging

fix another bug

---

configs/hello.yaml
docs/content/en/docs/QuickStart/_index.md
docs/content/en/docs/References/manifest/main.js
docs/content/en/schemas/schema.json
docs/content/ko/docs/QuickStart/_index.md
docs/content/ko/docs/References/manifest/main.js
examples/manifests/basic-example.yaml
examples/manifests/healthcheck-loadbalancer-example.yaml
examples/manifests/mixed-instances-policy-example.yaml
examples/manifests/spot-example.yaml
hack/schemas/main.go
pkg/aws/ec2.go
pkg/builder/builder.go
pkg/builder/builder_test.go
pkg/builder/config.go
pkg/deployer/bluegreen.go
pkg/initializer/initializer.go
pkg/runner/rurnner.go
pkg/tool/common.go
test/test_manifest.yaml

Fixes: #68 #69 
- add `tags` in stack config.
- remove ansible_tags from  examples and document (it will be deprecated)
- fix manifest file when `goployer init`

fix many hotfix problem

---

cmd/goployer/cmd/flag.go
cmd/goployer/cmd/status.go
docs/content/en/docs/References/commandline/_index.md
docs/content/ko/docs/References/commandline/_index.md
pkg/builder/builder.go
pkg/builder/config.go
pkg/runner/rurnner.go

- Add documentation about status command 
- Add `--auto-apply` flag which is only effective when a user runs `goployer deploy/delete` command from local terminal.

Add documentation about status command 

---

cmd/goployer/cmd/add.go
cmd/goployer/cmd/cmd.go
cmd/goployer/cmd/flag.go
cmd/goployer/cmd/init.go
cmd/goployer/cmd/status.go
docs/content/en/docs/References/commandline/_index.md
docs/content/ko/docs/References/commandline/_index.md
hack/apitest.sh
pkg/builder/builder.go
pkg/builder/config.go
pkg/initializer/initializer.go
pkg/runner/rurnner.go

- add `goployer add` command to create new manifest file to `manifests/` directory
```
$ goployer add 
$ goployer add test 
```

Add command

---

cmd/goployer/cmd/add.go
cmd/goployer/cmd/cmd.go
cmd/goployer/cmd/flag.go
cmd/goployer/cmd/init.go
docs/content/en/docs/QuickStart/_index.md
docs/content/en/docs/References/commandline/_index.md
docs/content/ko/docs/QuickStart/_index.md
docs/content/ko/docs/References/commandline/_index.md
hack/apitest.sh
pkg/initializer/initializer.go
pkg/runner/rurnner.go
pkg/tool/slack.go

- Add `SLACK_WEBHOOK_URL` environment variable for user to set up slack configuration with incoming webhook

Add slack with url

---

docs/content/ko/docs/References/commandline/_index.md
pkg/builder/builder.go

fix small issues

---

docs/content/en/docs/Install/_index.md
docs/content/ko/docs/Install/_index.md

Fixes: #88  
Remove theme file in order to keep clean code.

remove theme

---

cmd/goployer/cmd/flag.go
pkg/aws/aws.go
pkg/aws/cloudwatch.go
pkg/aws/dynamodb.go
pkg/aws/elbv2.go
pkg/collector/collector.go
pkg/constants/constants.go
pkg/deployer/deployer.go
pkg/inspector/inspector.go
pkg/tool/color.go

Fixes: #87  
Change  status format
```
$ goployer status hello
? Choose autoscaling group: hello-dev_apnortheast2-v001
Name:           hello-dev_apnortheast2-v001
Created Time:   2020-08-15 05:06:23.355 +0000 UTC
📦 Capacity
MINIMUM    DESIRED    MAXIMUM
2          2          2
🖥 Instance Statistics
∙ t3.large: 2
⚓ Tags
∙ Name=hello-dev_apnortheast2-v001
```

Change status format

---

deploy/cross/Dockerfile
pkg/aws/cloudwatch.go
pkg/collector/collector.go
pkg/runner/rurnner.go

Gathering metrics has an error that goployer collects only one day statistics.
Fix this bug

hotfix about metrics

---

pkg/deployer/deployer.go

Fix bug with printing instance healthy information to log

fix print host info bug

---

Makefile

fix Makefile because of wrong path of files

fix Makefile for release with version

---

pkg/aws/ec2.go

Allow value 0 for on demand percentage

allow zero for on demand percentage

---

docs/content/en/schemas/schema.json
pkg/deployer/deployer.go
pkg/tool/common.go

Add header section to api test
```
api_test_templates:
- name: api-test
duration: 5s
request_per_second: 10
apis:
- method: GET
url: http://localhost:8080
- method: POST
url: http://localhost:8080/post
body:
- id=198355
- username=dayone
- test=test
- method: Get
url: http://localhost:8080/check-headers
header:
- Authorization=bearer eyadsfJhbGc1NiIs6Ik...
- username=dayone
- test=test
```

add header to api test

---

pkg/deployer/deployer.go
pkg/schemas/config.go
test/test_manifest.yaml

Fixes: #116   
** Release Note **
```
Add termination policies in Region configuration.
```

add termination policies

---

docs/content/en/_index.html
docs/content/ko/_index.html
docs/layouts/partials/navbar.html

Update Logo and re-create introduction.

---

pkg/builder/builder.go
pkg/builder/builder_test.go
pkg/constants/constants.go
test/test_manifest.yaml

Fixes: #123  
User can use gp3 volume type in  goployer!!

aed gp3 for ebs volume

---

pkg/deployer/deployer.go
pkg/templates/templates.go

Hotfix on rolling update
Threshold should be the number of instances in Deploy process.

hotfix rolling update

---

Makefile
examples/manifests/deployonly-example.yaml
pkg/aws/ec2.go
pkg/deployer/deployer.go

- add feww debug message
- make IAM role optional

add few debug message

---

pkg/runner/runner.go
pkg/runner/runner_test.go

…outine, return error not just logging
Fixes: #nnn 
fixed when deploy and delete command execute if error occurred in goroutine, return error not just logging
in this PR apply, then error occurred not just logging and passing if region instance isn't match ami architecture(ex, region instance type t3, and ami architecture amd64)

fixed error occurred in goroutine

---

pkg/runner/runner.go

Handling error is enough to be done in deployment process.

fix error handling

---

pkg/deployer/deployer.go

Fixes: #nnn 
- fix comment and log message
- Log message "blokcDevice" is changed into "blockDevice"

fix comment

---

.github/workflows/tag_ci.yml
Makefile

Fixes: #nnn 
add ci pipeline for build binary and deploy to s3 bucket

feat: Add build and deploy ci

---

.github/CODEOWNERS
Makefile

**Related**: Version bump from `2.1.0` to `2.1.1`, CODEOWNERS update
- Updated release tag from `2.1.0` to `2.1.1` to reflect minor fixes and improvements.
- Modified `CODEOWNERS` file to update repository ownership rules.
**User facing changes**
Version updated:
- **Before**: `2.1.0`
- **After**: `2.1.1`
Ownership rules updated:
- `CODEOWNERS` file has been changed to reflect new code ownership assignments.
**Follow-up Work**
None

chore: rename tag from 2.1.0 to 2.1.1

---

Makefile

Fixes: #nnn 
When running the release-build command, the s3 command is incorrect, so fix that part.

fix: modify realase build cmd

---

Makefile
pkg/aws/ec2.go
pkg/deployer/deployer.go

Fixes: #nnn 
When creating a Launch Template, there is no resource tag, so there is no tag in the ebs volume that is created together. I implemented a function to add this.
Since the Launch template is not created when there is no KMS Alias, I will modify that part.

add resource tag for ebs
