README.md, configs/hello.yaml, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/deployer/bluegreen.go
Fixes: #3 
**Related**: lifecycle hooks feature
You could use `lifecycle hooks` feature of autoscaling group. This could be helpful if you have to do some stuff before launching or terminating instances like notification or upload logs to somewhere  etc.
=> add lifecycle hook feature

README.md, pkg/builder/builder.go, pkg/deployer/bluegreen.go
Fixes: #14  
add `--override-instance-type` in order to override instance type immediately with command. This could be needed when user wants to change instance type dynamically and frequently. 
User does not need to modify manifest file for changing instance type.
=> add override-instance-type arguement

.gitignore, configs/hello.yaml, go.mod, go.sum, metrics.yaml, pkg/aws/aws.go, pkg/aws/dynamodb.go, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/metric_builder.go, pkg/collector/collector.go, pkg/deployer/bluegreen.go, pkg/deployer/deployer.go, pkg/runner/rurnner.go, pkg/tool/common.go
Fixes: #16 
Gathering metrics of deployment is important to keep track of histories and those metrics could be used for many different usages. Currently it could be enabled by default, and user could disabled this with `--disable-metrics` argument from command line. 
Currently I added the following information.
- arguments applied from the command
- configurations from manifest file
- stack information user chose for deployment
- Deployment Status
- Deployment / Termination Timestamp
- Uptime for terminated autoscaling group.
=> create metrics for deployment

Makefile, README.md, configs/hello.yaml, docs/layouts/partials/page-meta-links.html, pkg/aws/dynamodb.go, pkg/builder/builder.go, pkg/builder/metric_builder.go, pkg/collector/collector.go, pkg/deployer/bluegreen.go, pkg/deployer/deployer.go, pkg/runner/rurnner.go
Add few features
1. `--release-notes`, `--release-notes-base64` added
: You can specify the release note for the deployment to explain the main features of this release.
: You cannot use both of these arguments at the same time.
2. Capacity of instances
- If current instance count is bigger than the number of instances in the manifest file, then bigger count will be applied. If you don't want this, then you could disable this feature with `--force-manifest-capacity=true` in the command line.
3. Userdata will be saved in the dynamodb table with base64 encoded.
=> Add few features

README.md, configs/hello.yaml, pkg/builder/builder.go, pkg/runner/rurnner.go, pkg/tool/common.go
Fixes: #5  
* User can control polling-interval for Health Check next 2ways.
* Add polling_interval field to stack manifest
* run goployer with --polling-interval param (It can be override to polling_interval of manifest file)
* Change type of `timeout value` int64 to time.Duration
```bash
INFO[0000] Beginning deployment: hello
============================================================
Target Stack Deployment Information
============================================================
name             : hello
env              : dev
timeout          : 60 min
polling-interval : 30 sec
assume role      :
extra tags       :
```
=> Add polling-interval param for health check

configs/hello.yaml, metrics.yaml, pkg/aws/aws.go, pkg/aws/cloudwatch.go, pkg/aws/dynamodb.go, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/metric_builder.go, pkg/collector/collector.go, pkg/deployer/bluegreen.go, pkg/deployer/deploy_manager.go, pkg/deployer/deployer.go, pkg/runner/rurnner.go, pkg/tool/common.go, server/main.go
Add request count of target group when terminating autoscaling group to statistics. Actually it is possible to add more than one autoscaling group to one target group so that this statistic could not be accurate. But AWS users can make as many target group as possible if they need because, as I know, the price of it is ignorable. 
So if we could guide users to match one autoscaling group to one target group then this statistics would be helpful for future usage.
The exact process is...
1. Get target group list  of autoscaling group.
2. Find the time duration how long this autoscaling group exists.
3. Starting with deployed date, get sum of request count for `a day` until terminated date for each target group.
- Statistics example
```
"stat": {
"targetgroup1": {
"m2020725": …
```
=> add request count of target group when terminating asg

pkg/aws/aws.go, pkg/runner/rurnner.go
Use assume role for aws cloudwatch api because we need to gather information about the target group in assumed account.
MetricClient in Collector has all AWS Client for gathering metrics and I  manually use `nil` to dynamodb client.
```
//Get all clients
client := MetricClient{
Region:            region,
DynamoDBService:   NewDynamoDBClient(aws_session, region, nil),
CloudWatchService: NewCloudWatchClient(aws_session, region, creds),
}
```
=> Hotfix apply assumerole for cloudwatch

configs/hello.yaml, hack/apitest.sh, pkg/aws/ec2.go, pkg/aws/elbv2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/deployer/bluegreen.go, pkg/deployer/deploy_manager.go, pkg/deployer/deployer.go, pkg/runner/rurnner.go, test/test_manifest.yaml
Fixes: #54  
If there is no target group specified, then skip healthcheck. This feature helps when a user wants to deploy autoscaling only without attaching target group such as bastion host.
I added few health check logic.
1. healthcheck_target_group cannot be empty if target_groups are not empty
2. target_groups cannot be empty if healthcheck_target_group is not empty
3. target_groups should contain healthcheck_target_group if neither of them is empty
User could deploy without target group.
=> add no target group deployment

examples/manifests/healthcheck-loadbalancer-example.yaml, hack/apitest.sh, pkg/aws/aws.go, pkg/aws/ec2.go, pkg/aws/elb.go, pkg/aws/elbv2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/deployer/bluegreen.go, pkg/deployer/deployer.go, test/test_manifest.yaml
Add classic LB support
If a user wants to deploy to classic load balancer, he/she could use `healthcheck_load_balancer` not `healthcheck_target_group`
=> add classic LB support

.gitignore, configs/hello.yaml, hack/apitest.sh, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/deployer/bluegreen.go, pkg/deployer/deploy_manager.go, pkg/deployer/deployer.go, pkg/runner/rurnner.go, pkg/tool/common.go, test/test_manifest.yaml
When deploying and deleting application, goployer used to run iteratively through whole deployers. This works well but if we support multi region and multi stack, this could be the bottle neck of malfunctioning. 
So I changed whole process to using goroutine and if a deployer fails from previous stack, then next step will be skipped. Only deployers which passed previous steps will continue to the next.
=> goployer apply goroutine for deploy/delete

pkg/builder/builder.go, pkg/deployer/bluegreen.go
- If `ENV` environment variable is set, then goployer automatically accept it with --env. This changes all the env value of stacks so that error occurred. So I removed  code related to the default setting for env
- If there is no autoscaling policy or  lifecycle hook setting, it returns nil without setting the step value to true. This is considered as failure, so that the next steps are skipped.
=> remove env setting and fix skipping issue

codebuild-buildspec-test.yml, configs/hello.yaml, examples/manifests/scheduled-actions-example.yaml, hack/apitest.sh, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/deployer/bluegreen.go, pkg/schemas/config.go, pkg/tool/common.go, test/test_manifest.yaml
Fixes: #84  
scheduling action is used when users want to control capacity based on schedules. Schedules are added based on cron expression.
You can specify scheduled_actions like below and specify the names of actions in the region configurations.
```
scheduled_actions:
- name: scale_in_during_weekend
recurrence: "0 9 * * SAT"
capacity:
min: 0
max: 0
desired: 0
- name: scale_out_during_weekday
recurrence: "0 9 * * MON"
capacity:
min: 1
max: 1
desired: 1
stacks:
- stack: artd
... 
regions:
- region: ap-northeast-2
instance_type: t3.medium
.... 
scheduled_actions:
- scale_in_during_weekend
- scale_out_during_weekday
```
Documentation because releasing
**Release notes**
```
Scheduled actions feature …
```
=> add scheduling feature

cmd/goployer/cmd/flag.go, pkg/aws/aws.go, pkg/aws/cloudwatch.go, pkg/aws/dynamodb.go, pkg/aws/elbv2.go, pkg/collector/collector.go, pkg/constants/constants.go, pkg/deployer/deployer.go
Currently, goployer collects RequestCountPerTarget which means the number of API calls in the instance among target group in average.
We need a total number of API calls in the load balancer in order to check all API calls.
=> fix cloudwatch metrics

pkg/aws/cloudwatch.go, pkg/deployer/bluegreen.go
Autoscaling alarm is created with same name so that policies in the autoscaling group are removed if other autoscaling group is created.
Fixed it
=> fix autoscaling alarm bug:

cmd/goployer/cmd/cmd.go, cmd/goployer/cmd/flag.go, configs/hello.yaml, docs/content/en/docs/References/commandline/_index.md, docs/content/en/schemas/metric.json, docs/content/en/schemas/schema.json, docs/content/ko/docs/References/commandline/_index.md, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/constants/constants.go, pkg/deployer/deployer.go, pkg/schemas/config.go, test/test_manifest.yaml
Fixes: #86  
Support io2 volume type. And add alias of `log-level` with `v`. Any command could be used with `-v info|debug|warning...`. Default value of log is changed from info to warning.
**Additional**
- Modify documentations
**Release Note**
```
- support io2 volume type.
- add iops configuration in the manifest file for supporting iops-required volume type
- Add alias of `log-level` with `v`. Any command could be used with `-v info|debug|warning...`. Default value of log is changed from info to warning
```
=> add io2 and modify documentation

cmd/goployer/cmd/status.go, configs/hello.yaml, pkg/aws/cloudwatch.go, pkg/aws/dynamodb.go, pkg/aws/ec2.go, pkg/constants/constants.go, pkg/inspector/inspector.go, pkg/runner/rurnner.go, pkg/tool/color.go
Fixes: #104  
Add security group information in `goployer status` 
This could help users to find the ingress/egress information with api call 
Sample result
```
$ ./goployer status hello
? Choose autoscaling group: hello-dev_apnortheast2-v001
Name:           hello-dev_apnortheast2-v001
Created Time:   2020-09-17 07:06:58.908 +0000 UTC
📦 Capacity
MINIMUM    DESIRED    MAXIMUM
1          1          2
🖥 Instance Statistics
∙ t3a.medium: 1
⚓ Tags
∙ Name=hello-dev_apnortheast2-v001
∙ ansible-tags=all
∙ app=hello
∙ project=test
∙ repo=hello-deploy
∙ stack=_apnortheast2
∙ stack-name=artd
∙ test=test
🚥 Inbound Rules
ID                        PROTOCOL   FROM    TO …
```
=> add security group information to status command

.gitignore, configs/hello.yaml, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/schemas/config.go, pkg/slack/slack.go
API Test configuration error occurred when there is no `api_test_templates` 
This could have an effect on all manifest files.
=> hotfix api test configuration error

cmd/goployer/cmd/cmd.go, cmd/goployer/cmd/flag.go, cmd/goployer/cmd/refresh.go, pkg/aws/ec2.go, pkg/constants/constants.go, pkg/inspector/inspector.go, pkg/refresh/refresh.go, pkg/runner/runner.go, pkg/schemas/config.go, pkg/templates/templates.go, pkg/tool/common.go
Fixes: #120  
Instance Refresh is the feature which changes instances of autoscaling without changing capacity manually. This helps when user wants to change instance with the new one or move VM to other place.
**Usage**
```
❯ goployer refresh hello -v debug --auto-apply --instance-warmup=120 --polling-interval=20s
INFO[0000] Goployer {Version: BuildDate: GitCommit: GitTreeState: Platform:darwin/amd64} 
DEBU[0000] Start to trigger instance refresh            
DEBU[0000] Instance Warmup time: 120s                   
DEBU[0000] Minimum healthy instance percentage: 90s     
DEBU[0003] Start to check instance refresh status       
DEBU[0003] Current time: 2020-11-18 11:05:01.878251 +0900 KST m=+3.880962992 / Timeout: 1h0m0s 
DEBU[0003] Polling interval: 20s …
```
=> add instance restart

.gitignore, Makefile, examples/manifests/basic-example.yaml, pkg/builder/builder.go, pkg/constants/constants.go, pkg/deployer/bluegreen.go, pkg/deployer/canary.go, pkg/deployer/deployer.go, pkg/deployer/rollingupdate.go, pkg/refresh/refresh.go, pkg/runner/runner.go
Now, goployer supports rolling update deployment!!
Anyone can use this by setting replacement_type to "RollingUpdate"
Rolling update will create one instance only first and start rolling update with previous instances.
=> add rolling update deployment

examples/manifests/rollingupdate-example.yaml, pkg/builder/builder.go, pkg/deployer/bluegreen.go, pkg/deployer/canary.go, pkg/deployer/deployer.go, pkg/deployer/deployer_test.go, pkg/deployer/rollingupdate.go, pkg/runner/runner.go, pkg/schemas/config.go
Add rolling update instance count option in order for users to run rolling update with custom instance count.
Users can use `rolling_update_instance_count` in stack configuration. If replacement_type is not `RollingUpdate`, then this configuration will be ignored. If it is and `rolling_update_instance_count` is null, then `1` will be applied.
=> add rolling update instance count

docs/content/en/schemas/schema.json, examples/manifests/basic-example.yaml, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/deployer/canary.go, pkg/deployer/deployer.go, pkg/schemas/config.go
Add `termination_delay_rate` options for BlueGreen deployment. 
This is helpful when users want to deploy with BlueGreen strategy but terminate instances gradually in order to keep stateful status.
If instance count is 10 and `termination_delay_rate` is 20, then first it provisions 10 more instances for Blue status. After all of instances are healthy, then reduce the instance count of Green status. At this time, goployer will reduce only 2 instances ( 20% of 10 instances) and check if those instances are successfully terminated.
=> add termination_delay_rate option

examples/manifests/deployonly-example.yaml, pkg/aws/elbv2.go, pkg/constants/constants.go, pkg/deployer/canary.go, pkg/deployer/deployer.go, pkg/deployer/deployonly.go, pkg/runner/runner.go
We add a new replacement type `DeployOnly`. This can be used when there is no health check process like bastion server, sample test service for local development, etc.
With `DeployOnly` type, goployer will skip healthcheck process. It will provision a new version of autoscaling and delete the previous versions right away. It still checks whether all instances are successfully terminated.
Add end to end test code for deployonly type
=> add deployonly type

pkg/aws/ec2.go
Keypair for EC2 instance is optional. It means that if there is no keypair, then goployer should launch instances with no keypair.
=> make keypair optional

cmd/goployer/cmd/flag.go, pkg/aws/ec2.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/constants/constants.go, pkg/deployer/deployer.go, pkg/deployer/deployer_test.go, pkg/schemas/config.go
Fixes: #136  
Mixed instance policy have override instance type, but this option cannot override in runtime. 
So, in this PR i implement instance type in mixed instance policy override in runtime.
multiple type also accept. but, only use same instance types.(arm64 and x86_64 cannot use at the same time)
ex) --override-spot-types="t2.nano|t3.large"
User use this option, then dynamically change spot instance type in goployer!!
=> add spot override instace types option

deploy/Dockerfile, pkg/aws/ec2.go, pkg/deployer/deployer.go, pkg/schemas/config.go
Fixes: #nnn 
When provisioning ec2, the function to encrypt ebs has been modified.
By default, encrypted: true and when there is no kmsAlias, it is encrypted with alias/aws/ebs, and when kmsAlias ​​is specified, it is encrypted with the corresponding kms key.
A policy that ListAlias ​​the IAM Role used when deploying is required.
=> modify ebs encryption logic

README.md, examples/manifests/api-test-example.yaml, pkg/aws/ec2.go, pkg/aws/ec2_test.go, pkg/schemas/config.go
Fixes: #154 
**Related**: #154 
**Merge before/after**: None
This PR implements the EBS volume management enhancement requested in #154, adding two key features:
1. DeleteOnTermination Support
- Added `DeleteOnTermination` field to `BlockDevice` struct
- Implemented in both `MakeLaunchTemplateBlockDeviceMappings` and `MakeBlockDevices`
- Default value is `false` (volumes are preserved on instance termination)
- Optional configuration in manifest files
2. Snapshot Support
- Added support for creating EBS volumes from existing snapshots
- Implemented in both launch template and launch configuration
- Allows for data persistence and volume restoration
**User facing changes**
Before:
```yaml
block_devices:
- device_name: /dev/xvda
volume_size: 30
volume_type: gp3
```
After: …
=> feat: enhance EBS volume management capabilities

Makefile
Fixes: #nnn 
when execute release-build, disable docker build.
Because docker image not using current.
=> disable docker build when release-build

Makefile, pkg/aws/ec2.go, pkg/aws/ec2_test.go, pkg/deployer/deployer.go, pkg/schemas/config.go
This PR enforces IMDSv2 (Instance Metadata Service Version 2) for all EC2 instances deployed via goployer by adding metadata options to the launch template configuration.
**Changes:**
- Added `MetadataOptions` field to `CreateNewLaunchTemplate` function in `pkg/aws/ec2.go`
- Set `HttpTokens: "required"` to enforce IMDSv2 token-based authentication
- Set `HttpPutResponseHopLimit` with configurable default of 1 for security hardening
- Set `HttpEndpoint: "enabled"` to keep metadata service accessible
- Added `HttpPutResponseHopLimit` field to `RegionConfig` schema for user configuration
**Security Benefits:**
- Prevents SSRF (Server-Side Request Forgery) attacks targeting IMDS
- Requires session tokens for metadata access, improving security posture
- Aligns with AWS …
=> add metadata options to launch template creation

Makefile, pkg/aws/ec2.go, pkg/deployer/deployer.go, pkg/deployer/deployer_test.go, pkg/sumdb/sum.golang.org/latest
Fixes: #nnn 
Goployer is Default timeout 3600s(1h). When Deploy EC2 cannot healtch before timeout, then goployer remove previous AutoSacligGroup. 
So, Service return 503, and unavailble status. 
In this PR, stroe healtcheck flag and check flag for remove previous auto scaling group
=> feat:modify remove previous asg after goployer timeout
